words = (
    "abacus", "abandon", "abbreviate", "abnormal", "abolish", "abound", "abrasive", "absent", "absorb", "abstract",
    "abundant", "academy", "accelerate", "accent", "accept", "access", "acclaim", "accommodate", "accompany", "accomplish",
    "accord", "account", "accuse", "achieve", "acquire", "acquit", "acronym", "activate", "adapt", "addict",
    "address", "advance", "adverse", "advice", "advocate", "aesthetic", "affable", "affect", "afford", "against",
    "agency", "agenda", "aggravate", "aggregate", "agile", "agitate", "allegory", "allocate", "allude", "amass",
    "amaze", "ambiguous", "amplify", "analyze", "anatomy", "ancient", "animate", "annex", "anomaly", "anxiety",
    "apathy", "apex", "apologize", "appeal", "appoint", "approve", "aptitude", "arbitrary", "archive", "arrange",
    "articulate", "ascend", "assert", "assess", "assign", "assist", "assume", "assure", "astonish", "attain",
    "attempt", "attract", "augment", "authentic", "authorize", "autonomous", "avert", "balance", "banish", "barrier",
    "batter", "benefit", "bilingual", "bless", "bother", "boundary", "brilliant", "broaden", "bypass", "calculate",
    "candid", "capture", "catalyst", "caution", "celebrate", "censor", "ceremony", "chaotic", "chronic", "clarify",
    "classify", "coerce", "coherent", "collaborate", "commend", "compel", "compete", "compile", "comprehend", "conceal",
    "conclude", "concrete", "confess", "conform", "confuse", "conquer", "conscience", "conserve", "consider", "consolidate",
    "construct", "consult", "consume", "contact", "contain", "contemplate", "continue", "contradict", "contribute", "convert",
    "convince", "correlate", "corrupt", "counsel", "create", "critique", "cultivate", "cynical", "debate", "decipher",
    "defend", "deficit", "defuse", "deliberate", "demand", "dementia", "denote", "deplete", "deprive", "derive",
    "deter", "detract", "devastate", "dilemma", "diminish", "diploma", "direct", "disclose", "discuss", "dismantle",
    "distract", "divert", "dominate", "duplicate", "dwell", "elaborate", "eliminate", "emerge", "empathy", "enact",
    "enclose", "encourage", "endorse", "enforce", "engage", "enhance", "enlighten", "enlist", "enrich", "ensign",
    "entail", "entice", "envision", "equate", "evaluate", "examine", "exceed", "exclude", "excuse", "exempt",
    "exhibit", "expand", "explore", "expose", "extend", "extract", "facilitate", "fascinate", "fathom", "favorable",
    "feasible", "federal", "finesse", "flourish", "forbid", "forgive", "fortify", "fracture", "frequent", "frustrate",
    "gather", "genuine", "generate", "glisten", "graft", "grasp", "gratify", "grouse", "guilt", "harmony",
    "hesitate", "hinder", "horizon", "hospitable", "hostile", "humble", "hurdle", "hypothesis", "ignite", "illustrate",
    "immerse", "impact", "impose", "impress", "improve", "incentive", "incite", "include", "influence", "inform",
    "inject", "inquire", "insight", "inspect", "inspire", "install", "integrate", "intend", "interact", "intervene",
    "introduce", "involve", "irritate", "isolate", "jargon", "jeopardize", "juggle", "justify", "keen", "knead",
    "knit", "knowledge", "languish", "launch", "lecture", "legitimate", "leverage", "liberate", "literate", "locate",
    "lure", "magnify", "maintain", "manipulate", "mediate", "merit", "method", "modify", "monitor", "motivate",
    "navigate", "negotiate", "nurture", "observe", "obtain", "offset", "oppose", "optimize", "organize", "overcome",
    "overlook", "oversee", "participate", "perceive", "perform", "persist", "persuade", "ponder", "predict", "prescribe",
    "presume", "proceed", "procrastinate", "profound", "progress", "prohibit", "promote", "propose", "protect", "provoke",
    "pursue", "qualify", "question", "quote", "reassure", "rebel", "recharge", "recollect", "reconcile", "recycle", "reduce",
    "reflect", "reform", "refuse", "regulate", "rejoice", "relate", "reluctant", "remedy", "remove", "reorganize",
    "replenish", "reproduce", "rescue", "reside", "resolve", "restore", "restrict", "retain", "reveal", "revise",
    "safeguard", "satisfy", "secure", "select", "separate", "simulate", "simplify", "sincere", "situation", "sponsor",
    "stimulate", "subdue", "subsidize", "succeed", "suspend", "sustain", "synchronize", "synthesize", "tolerate", "transform",
    "translate", "uncover", "undergo", "understand", "unite", "unveil", "utilize", "verify", "vibrate", "vigilant", "vocalize",
    "volunteer", "vulnerable", "warrant", "warranted", "weaken", "welfare", "withstand", "withdraw", "witness", "zealot"
)

x = 0
while x < len(words):
    x += 1
print(x)